name: Github Actions
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: jiro4989/setup-nim-action@v1
    - run: nimble test -d:release -y
    - run: nimble test -d:release -d:pixieNoSimd -y
    - run: nimble test --gc:orc -d:release -y
    - run: nim cpp -d:release -r tests/all.nim
    - shell: bash
      run: |
        nimble install winim wNim
        for nimfile in $(ls examples/*.nim); do
          echo "Testing $nimfile"
          nim --path:$(pwd)/src check $nimfile
        done
